version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: shopsphere-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopsphere
    ports:
      - "5432:5432"
    volumes:
      - shopsphere-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  shopsphere-db-data:
